/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from '@react-three/fiber';
// @ts-ignore
export function SatelliteScene(props) {
  const { nodes, materials } = useGLTF("/Station.glb");
  
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.InternationalSpaceStation_mesh.geometry}
        material={materials.InternationalSpaceStation_mat}
      />
    </group>
  );
}

useGLTF.preload("/Station.glb");
